SistemaWebVuelos/Models/AdmVuelo.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using SistemaWebVuelos.Models;
using SistemaWebVuelos.Data;

namespace SistemaWebVuelos.Models
{
    public static class AdmVuelo
    {
        private static VueloDbContext context = new VueloDbContext();
        public static List<Vuelo> Listar()
        {
            return context.Vuelos.ToList();
        }
        public static Vuelo Listar(int id)
        {
            Vuelo vuelo = context.Vuelos.Find(id);
            context.Entry(vuelo).State = EntityState.Detached;
            return vuelo;
        }
        public static void Cargar(Vuelo vuelo)
        {
            context.Vuelos.Add(vuelo);
            context.SaveChanges();
        }
        public static void Modificar(Vuelo vuelo)
        {
            context.Vuelos.Attach(vuelo);
            context.Entry(vuelo).State = EntityState.Modified;
            context.SaveChanges();
        }
        public static void Borrar(Vuelo vuelo)
        {
            context.Vuelos.Attach(vuelo);
            context.Vuelos.Remove(vuelo);
            context.SaveChanges();
        }
        public static List<Vuelo> BuscarPorDestino(string destino)
        {
            var vuelo = (from v in context.Vuelos
                         where v.Destino == destino
                         select v).ToList();
            return vuelo;
        }
    }
}

SistemaWebVuelos/Models/Vuelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SistemaWebVuelos.Models
{
    
    public class Vuelo

    {
        public int Id { get; set; }

        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Fecha { get; set; }

        [Required]
        public string Destino { get; set; }
        [Required]
        public string Origen { get; set; }

        [Range(100, 1000, ErrorMessage = "The field PagesNumber must be between 100 and 1000")]
        public string Matricula { get; set; }



    }
}

SistemaWebVuelos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaWebVuelos.Models;

namespace SistemaWebVuelos.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Fecha = DateTime.Now.ToShortDateString();
            return View();
        }
    }
}

SistemaWebVuelos/Controllers/VueloController.cs
using SistemaWebVuelos.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaWebVuelos.Models;
using System.Data;
using SistemaWebVuelos.Filters;

namespace SistemaWebVuelos.Controllers
{
    [MyFilterAction]
    public class VueloController : Controller
    {

        private VueloDbContext context = new VueloDbContext();
        // GET: Vuelo
        public ActionResult Index()
        {
            return View("Index", AdmVuelo.Listar());
        }



        public ActionResult Create()
        {
            Vuelo vuelo = new Vuelo();
            return View("Create", vuelo);

        }

        [HttpPost]

        public ActionResult Create (Vuelo vuelo)
        {
            if(ModelState.IsValid)
            {
                AdmVuelo.Cargar(vuelo);
                return RedirectToAction("Index");

            }
            return View("Create", vuelo);

        }

        public ActionResult Detail(int id)
        {
            Vuelo vuelo = AdmVuelo.Listar(id);

            if (vuelo != null)
            {
                return View("Detail", vuelo);
            }
            else
            {
                return HttpNotFound();
            }
        }
        public ActionResult Delete(int id)
        {
            Vuelo vuelo = AdmVuelo.Listar(id);

            if (vuelo != null)
            {
                return View("Delete", vuelo);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Vuelo vuelo = AdmVuelo.Listar(id);
            if (vuelo != null)
            {
                AdmVuelo.Borrar(vuelo);
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult BuscarxDestino(string destino)
        {
            return View("Index", AdmVuelo.BuscarPorDestino(destino));

        }
        public ActionResult Edit(int id)
        {
            Vuelo vuelo = AdmVuelo.Listar(id);

            if (vuelo != null)
            {
                return View("Edit", vuelo);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        public ActionResult Edit(Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                AdmVuelo.Modificar(vuelo);
                return RedirectToAction("Index");
            }
            return View("Edit", vuelo);

        }
    }
}

SistemaWebVuelos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

        <h2>Fecha: @ViewBag.Fecha</h2>
        <h1>Bienvenidos al sitio web de Vuelos!</h1>

    

SistemaWebVuelos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <h1>SISTEMA VUELOS</h1>

    </div>
    <div id="menu">
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Vuelos", "Index", "Vuelo")
       
    </div>
    <div id="sidebar">

        @if (IsSectionDefined("Sidebar"))
        {
            @RenderSection("Sidebar")
        }
        else
        {
            <h2>Zona Editable Opcional</h2>

        }

    </div>
    <div>
        @RenderBody()
    </div>
    <div id="footer">
        
        <p>info@vuelo.com</p>

    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

SistemaWebVuelos/Views/Vuelo/Create.cshtml
@model SistemaWebVuelos.Models.Vuelo
<h2>Crear Nuevo Vuelo</h2>
    @using (Html.BeginForm("Create", "Vuelo", FormMethod.Post))
    {
      
        <div>
            @Html.LabelFor(model => model.Fecha)
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        <div>
            @Html.LabelFor(model => model.Destino)
            @Html.EditorFor(model => model.Destino)
            @Html.ValidationMessageFor(model => model.Destino)
        </div>
        <div>
            @Html.LabelFor(model => model.Origen)
            @Html.EditorFor(model => model.Origen)
            @Html.ValidationMessageFor(model => model.Origen)
        </div>
        <div>
            @Html.LabelFor(model => model.Matricula)
            @Html.EditorFor(model => model.Matricula)
            @Html.ValidationMessageFor(model => model.Matricula)
        </div>
        <p><input type="submit" value="Guardar" /> </p>
      

    }

    @Html.ActionLink("Volver al Index", "Index", "Vuelo")

SistemaWebVuelos/Views/Vuelo/Delete.cshtml
@model SistemaWebVuelos.Models.Vuelo

    <h2> Eliminar Vuelo </h2>
    
    @using (Html.BeginForm("Delete", "Vuelo", FormMethod.Post))
    {<fieldset>
    <p>Está seguro que Desea Eliminar?</p>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Id)
    </div>
    <div class="display-text">
        @Html.DisplayFor(model => model.Id)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-text">
        @Html.DisplayFor(model => model.Fecha)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Destino)
    </div>
    <div class="display-text">
        @Html.DisplayFor(model => model.Destino)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Origen)
    </div>
    <div class="display-text">
        @Html.DisplayFor(model => model.Origen)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Matricula)
    </div>
    <div class="display-text">
        @Html.DisplayFor(model => model.Matricula)
    </div>
</fieldset>

        <p>
            <input type="submit" value="Si" />
        </p>
    }
    <p>
        @Html.ActionLink("Volver al Index", "Index", "Vuelo")
    </p>

SistemaWebVuelos/Views/Vuelo/Detail.cshtml
@model SistemaWebVuelos.Models.Vuelo

    <fieldset>
        <legend>Detalles del Vuelo</legend>
        <div id="detail">
            <p><b> @Html.DisplayNameFor(model => model.Id):</b>@Html.DisplayFor(model => model.Id)</p>
        </div>
        
        <div id="detail">
            <p><b> @Html.DisplayNameFor(model => model.Fecha):</b> @Html.DisplayFor(model => model.Fecha)</p>
</div>
        
        <div id="detail">
            <p><b> @Html.DisplayNameFor(model => model.Destino):</b>@Html.DisplayFor(model => model.Destino)</p>
</div>
        
        <div id="detail">
            <p><b> @Html.DisplayNameFor(model => model.Origen):</b>@Html.DisplayFor(model => model.Origen)</p>
</div>
        
        
        <div id="detail">
            <p><b> @Html.DisplayNameFor(model => model.Matricula):</b>@Html.DisplayFor(model => model.Matricula)</p>
</div>
        

    </fieldset>
    <p>
        @Html.ActionLink("Volver a Index", "Index", "Vuelo")

    </p>

SistemaWebVuelos/Views/Vuelo/Edit.cshtml
@model SistemaWebVuelos.Models.Vuelo

@using (Html.BeginForm("Edit", "Vuelo", FormMethod.Post))

{
    @Html.HiddenFor(model => model.Id)
    <div>
        @Html.LabelFor(model => model.Fecha)
        @Html.EditorFor(model => model.Fecha)
        @Html.ValidationMessageFor(model => model.Fecha)
    </div>
    <div>
        @Html.LabelFor(model => model.Origen)
        @Html.EditorFor(model => model.Origen)
        @Html.ValidationMessageFor(model => model.Origen)
    </div>
    <div>
        @Html.LabelFor(model => model.Destino)
        @Html.EditorFor(model => model.Destino)
        @Html.ValidationMessageFor(model => model.Destino)
    </div>
    <div>
        @Html.LabelFor(model => model.Matricula)
        @Html.EditorFor(model => model.Matricula)
        @Html.ValidationMessageFor(model => model.Matricula)
    </div>

    <p>
        <input type="submit" name="Edit" value="Enviar" />
    </p>

}
@Html.ActionLink("Volver a la lista", "Index", "Vuelo")

SistemaWebVuelos/Views/Vuelo/Index.cshtml
@model IEnumerable<SistemaWebVuelos.Models.Vuelo>

    <p>@Html.ActionLink("Nuevo", "Create", "Vuelo")</p>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Fecha)</th>
            <th>@Html.DisplayNameFor(model => model.Destino)</th>
            <th>@Html.DisplayNameFor(model => model.Origen)</th>
            <th>@Html.DisplayNameFor(model => model.Matricula)</th>
            <th>Details</th>
            <th>Delete</th>
            <th>Edit</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                <td>@Html.DisplayFor(modelItem => item.Destino)</td>
                <td>@Html.DisplayFor(modelItem => item.Origen)</td>
                <td>@Html.DisplayFor(modelItem => item.Matricula)</td>
                <td>@Html.ActionLink("Detail", "Detail", new { id = item.Id })</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</td>

            </tr>

        }
        
    </table>